Repository RaidAndFade/OctoberChallenges2019, pull requests merged in 2019-09, with the labels that each got.

#3 JS
  Yes/yes.js
  contributors.md
Labels: attention, contriblist, week1

#14 Add C++ version of the solution
  Yes/yes.cpp
  contributors.md
Labels: attention, contriblist, week1

#15 Added contributor
  Yes/yes.ts
  contributors.md
Labels: attention, contriblist, week1

#4 Update contributors.md
  contributors.md
Labels: attention, contriblist

#8 Added C version
  Yes/yes.c
Labels: attention, week1

#9 Added Rust
  Yes/yes.rs
Labels: attention, week1

#5 adding php-version
  Yes/yes.php
  contributors.md
Labels: attention, contriblist, week1

#16 Create yes in Dart
  Yes/yes.dart
Labels: attention, week1
