Repository RaidAndFade/OctoberChallenges2019, pull requests merged in 2019-10, with the labels that each got.

#17 Added c# version
  Yes/yes.cs
  contributors.md
Labels: contriblist, needs work, week1

#19 yes in bash
  Yes/yes.sh
Labels: attention, week1

#20 Update contributors.md
  contributors.md
Labels: attention, contriblist

#25 Added Ruby language
  Yes/yes.rb
  contributors.md
Labels: attention, contriblist, week1

#6 Yes in java
  Yes/yes.java
  contributors.md
Labels: contriblist, needs work, week1

#28 Added Yes in Go Lang.
  Yes/yes.go
Labels: attention, week1

#37 Just say yes in Lua
  Yes/yes.lua
Labels: attention, week1

#38 Added yes in Brainfuck
  Yes/yes.bf
  contributors.md
Labels: attention, contriblist, week1

#35 add kotlin
  Yes/yes.kt
Labels: needs work

#34 Yes perl
  Yes/yes.pl
  contributors.md
Labels: contriblist, needs work, week1

#49 creat yes.jl
  Yes/yes.jl
  contributors.md
Labels: attention, contriblist, week1

#99 Testing the auto-audit system
  contributors.md
Labels: contriblist, needs work

#101 Created the "Yes" program in MIPS Assembly
  Yes/yes.masm
  contributors.md
Labels: contriblist, needs work, week1

#21 Add D version
  Yes/yes.d
Labels: attention, week1

#39 Yes in F#
  Yes/yes.fs
  contributors.md
Labels: attention, contriblist, week1

#41 Yes in VB
  Yes/yes.vb
Labels: attention, week1

#45 Added abhhii as a contributer
  contributors.md
Labels: attention, contriblist, improper

#43 Added yes in batch
  Yes/yes.bat
Labels: attention, week1

#46 add yes program in pascal and update contributors.md
  Yes/yes.pas
  contributors.md
Labels: attention, contriblist, week1

#78 Added yes in R
  Yes/yes.R
Labels: attention, week1

#47 Yes in Swift
  Yes/yes.swift
  contributors.md
Labels: attention, contriblist, week1

#50 Created Objective-C file
  Yes/yes.m
Labels: attention, week1

#51 Update Contributors.md :)
  contributors.md
Labels: attention, contriblist, improper

#52 Yes-Scala
  Yes/yes.scala
  contributors.md
Labels: attention, contriblist, week1

#54 Update contributors.md
  Yes/yes.m
  contributors.md
Labels: attention, contriblist, week1

#59 Add yes in Fortran
  Yes/yes.f95
  contributors.md
Labels: attention, contriblist, week1

#64 Create yes.v
  Yes/yes.v
Labels: attention, week1

#68 Added pascal
  Yes/yes.pp
  contributors.md
Labels: attention, contriblist, week1

#71 batch
  Yes/yes.bat
  contributors.md
Labels: attention, contriblist, week1

#72 GameMaker Language
  Yes/yes.gml
  contributors.md
Labels: attention, contriblist, week1

#73 Yes in Powershell
  Yes/yes.ps1
  contributors.md
Labels: attention, contriblist, week1

#83 Kat35601
  Yes/yes.sql
Labels: attention, week1

#91 Added yes for OpenScad.
  Yes/yes.scad
  contributors.md
Labels: attention, contriblist, week1

#93 added yes in Nim
  Yes/yes.nim
Labels: attention, week1

#94 Added yes in groovy
  Yes/yes.groovy
  contributors.md
Labels: attention, contriblist, week1

#102 Yes in ArnoldC
  Yes/yes.arnoldc
Labels: attention, week1

#116 Add Lisp
  Yes/yes.lisp
  contributors.md
Labels: attention, contriblist, week1

#117 Added Yes in Scheme Prog language
  Yes/yes.scm
Labels: attention, week1

#112 Yes in Coffeescript
  Yes/yes.coffee
Labels: attention, week1
